version: '3'

services:
  web:
    container_name: web
    build: ./app/
    command: python manage.py runserver 0.0.0.0:8001 --noreload
    expose:
      - "8001"
    ports:
      - 8001:8001

  postgres:
    image: postgres:16
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=avido_db

volumes:
  postgres_volume:
