version: '3'

services:
  web:
    container_name: web
    build: ./app/
    command: gunicorn avido.wsgi --bind 0.0.0.0:8001
    expose:
      - 8001
    ports:
      - 8001:8001
    env_file:
      - ./app.env
    depends_on:
      - postgres
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles

  postgres:
    image: postgres:16
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    ports:
      - 5431:5432
    env_file:
      - ./app.env

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles

volumes:
  postgres_volume:
  static_volume:
  media_volume:
